const fakeData = [
  {
    name: 'Hyuk',
    comment: 'comment',
    picture: 'pic',
    date: 'Sat Jul 07 1962 01:30:17 GMT-',
    accuracy: 3,
    communication: 4,
    cleanliness: 5,
    location: 2,
    check_in: 5,
    value: 4,
    average: 4,
  },
  {
    name: 'Allison',
    comment: 'comment',
    picture: 'pic',
    date: 'Sat Jul 07 1962 01:30:17 GMT-',
    accuracy: 1,
    communication: 3,
    cleanliness: 2,
    location: 4,
    check_in: 5,
    value: 2,
    average: 3,
  },
  {
    name: 'Thaki',
    comment: 'comment',
    picture: 'pic',
    date: 'Sat Jul 07 1962 01:30:17 GMT-',
    accuracy: 4,
    communication: 1,
    cleanliness: 5,
    location: 2,
    check_in: 4,
    value: 1,
    average: 3,
  },
  {
    name: 'Brian',
    comment: 'comment',
    picture: 'pic',
    date: 'Sat Jul 07 1962 01:30:17 GMT-',
    accuracy: 5,
    communication: 5,
    cleanliness: 5,
    location: 1,
    check_in: 2,
    value: 4,
    average: 4,
  },
];

export default fakeData;
